const CATALOG = [
  {
    id: "nike1",
    name: "Nike SB Dunk Low Colourful",
    price: 2399,
    extra: 0,
    img: "./products/nike-dunk-sb-low-cf.jpg",
    sizes: [6, 7, 8, 9],
  },
  {
    id: "nike2",
    name: "Nike SB Dunk Low x Otomo Katsuhiro",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-x-otomo-katsuhiro.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike3",
    name: "Nike SB Dunk Low Greyish",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-greyish.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike4",
    name: "Nike SB Dunk Low x Otomo Katsuhiro",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-otomo.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike5",
    name: "Nike SB Dunk Low Custom 2025",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-custom-2025.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike6",
    name: "Nike SB Dunk Low Born x Raised",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-born-x-raised.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike7",
    name: "Nike SB Dunk Low Stussy Grey Orange",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-stussy-grey-orange.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike8",
    name: "Nike SB Dunk Low Year of the Snake",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-year-of-the-snake.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike9",
    name: "Nike SB Dunk Custom 2025 The Wolf",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-custom-2025-the-wolf.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike10",
    name: "Nike Air Jordan Retro",
    price: 2399,
    extra: 0,
    img: "./products/nike-air-jordan-retro.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike11",
    name: "Nike SB Dunk 94 Charcoal Grey",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-94-charcoal-grey.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike12",
    name: "Nike SB Dunk Ambush Custom",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-ambush-custom.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike13",
    name: "Nike SB Dunk Court Purple",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-court-purple.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike14",
    name: "Nike SB Dunk Renown Mazda",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-renown-mazda.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike15",
    name: "Nike SB Dunk Low Snowman",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-snowman.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike16",
    name: "Nike SB Dunk Low Love & Peace",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-love-and-peace.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike17",
    name: "Nike SB Dunk Low Light Orewood Brown Sashiko",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-light-orewood-brown-sashiko.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike18",
    name: "Nike SB Dunk Low Dusty Olive",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-dusty-olive.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike19",
    name: "Jordan Jumpman Jack TP Travis Scott Dark Mocha",
    price: 2699,
    extra: 300,
    img: "./products/jordan-jumpman-jack-tp-travis-scott-dark-mocha.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike20",
    name: "Nike Airforce Big Bank Chunky",
    price: 2599,
    extra: 200,
    img: "./products/nike-airforce-big-bank-chunky.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
];

const OFFER_CATALOG = [
  {
    id: "offer-nike1",
    name: "Nike Dunk Low Blue and White",
    price: 0,
    extra: 0,
    img: "./offer-products/nike1.jpg",
    sizes: [10],
  },
  {
    id: "offer-adidas1",
    name: "Adidas Samba Brown",
    price: 0,
    extra: 0,
    img: "./offer-products/adidas1.jpg",
    sizes: [9],
  },
  {
    id: "offer-puma1",
    name: "Puma Speedcat Black and White",
    price: 0,
    extra: 100,
    img: "./offer-products/puma1.jpg",
    sizes: [9, 10],
  },
  {
    id: "offer-jordan1",
    name: "Jordan Mid Black",
    price: 0,
    extra: 300,
    img: "./offer-products/jordan1.jpg",
    sizes: [9],
  },
  {
    id: "offer-nike2",
    name: "Nike Jordan 1 Low",
    price: 0,
    extra: 50,
    img: "./offer-products/nike2.jpg",
    sizes: [8],
  },
  {
    id: "offer-adidas2",
    name: "Adidas Campus Light Brown",
    price: 0,
    extra: 0,
    img: "./offer-products/adidas2.jpg",
    sizes: [10],
  },
  {
    id: "offer-puma2",
    name: "Puma Speedcat Red and White",
    price: 0,
    extra: 0,
    img: "./offer-products/puma2.jpg",
    sizes: [9, 10],
  },
  {
    id: "offer-jordan2",
    name: "Jordan Air 4 Black Cat",
    price: 0,
    extra: 0,
    img: "./offer-products/jordan2.jpg",
    sizes: [7],
  },
  {
    id: "offer-nike3",
    name: "Nike Custom Air Force",
    price: 0,
    extra: 0,
    img: "./offer-products/nike3.jpg",
    sizes: [6],
  },
  {
    id: "offer-adidas3",
    name: "Adidas Campus Black and White",
    price: 0,
    extra: 100,
    img: "./offer-products/adidas3.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "offer-puma3",
    name: "Puma Speedcat Peach and White",
    price: 0,
    extra: 0,
    img: "./offer-products/puma3.jpg",
    sizes: [6],
  },
  {
    id: "offer-nike4",
    name: "Nike Air Jordan Retro Low",
    price: 0,
    extra: 0,
    img: "./offer-products/nike4.jpg",
    sizes: [5, 6],
  },
  {
    id: "offer-adidas4",
    name: "Adidas Forum Low White and Black",
    price: 0,
    extra: 100,
    img: "./offer-products/adidas4.jpg",
    sizes: [7],
  },
  {
    id: "offer-nike5",
    name: "Nike Dunk low Greyish",
    price: 0,
    extra: 0,
    img: "./offer-products/nike5.jpg",
    sizes: [8],
  },
  {
    id: "offer-adidas5",
    name: "Adidas Samba Greyish Green",
    price: 0,
    extra: 0,
    img: "./offer-products/adidas5.jpg",
    sizes: [8, 9],
  },
  {
    id: "offer-nike6",
    name: "Nike Dunk Low Full Black",
    price: 0,
    extra: 100,
    img: "./offer-products/nike6.jpg",
    sizes: [9],
  },
  {
    id: "offer-adidas6",
    name: "Adidas Samba Olive Green Suede",
    price: 0,
    extra: 0,
    img: "./offer-products/adidas6.jpg",
    sizes: [10],
  },
  {
    id: "offer-nike7",
    name: "Nike Jordan Retro Low 1",
    price: 0,
    extra: 0,
    img: "./offer-products/nike7.jpg",
    sizes: [9],
  },
];
